### ISSUE TITLE
Error in loading the pretrained model

### ISSUE THREAD

**Issue by sedflix** [koomri/text-segmentation#1]
While trying to load the model given [here](https://www.dropbox.com/sh/k3jh0fjbyr0gw0a/AADzAd9SDTrBnvs1qLCJY5cza?dl=0), I'm facing the following problem: 
```
.....
.....
  File "/home/sid/text-segmentation/evaluate.py", line 13, in load_model
    model = torch.load(f)
  File "/home/sid/miniconda2/envs/textseg/lib/python2.7/site-packages/torch/serialization.py", line 261, in load
    return _load(f, map_location, pickle_module)
  File "/home/sid/miniconda2/envs/textseg/lib/python2.7/site-packages/torch/serialization.py", line 399, in _load
    magic_number = pickle_module.load(f)
cPickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```

**Comment by koomri** [comment]
I could not reproduce this problem. Did you install the right torch package? can you send the full stack? can you load models from other flow paths (e.g test_accuracy.py)

**Comment by sedflix** [comment]
I tried loading the model through several flow paths. Each time the above part was common in them.

I installed the torch package given the README.md file. Right now, I'm using docker to run it ([Dockerfile](https://github.com/geekSiddharth/text-segmentation/blob/master/Dockerfile)).  I was getting the same error while using conda env.

Stack for test_accuracy.py:

```
  File "test_accuracy.py", line 178, in <module>
    main(parser.parse_args())
  File "test_accuracy.py", line 79, in main
    model = torch.load(f)
  File "/usr/local/lib/python2.7/site-packages/torch/serialization.py", line 261, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python2.7/site-packages/torch/serialization.py", line 399, in _load
    magic_number = pickle_module.load(f)
cPickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```

Does it have something do with the way the model was saved? (Maybe they cannot be loaded if not present at the same path where they were saved initially) As given [here](https://pytorch.org/docs/stable/notes/serialization.html) in the last section. 

```
However in this case, the serialized data is bound to the specific classes and the exact directory 
structure used, so it can break in various ways when used in other projects, or after some serious 
refactors.
```

**Comment by koomri** [comment]
I don't think that it is related, since I can run the flow on various machines. Can you add the command that you are running?

**Comment by sedflix** [comment]
It's same as given in the README file(with a proper model path). 

I was able to use models trained by me locally using the very same command.

**Comment by sedflix** [comment]
Config file:
```
root@f2f8e97440dc:/datadrive/sid/text-segmentation# cat configgenerator.py
import json

jsondata = {
    "word2vecfile": "/datadrive/sid/embedding",
    "choidataset": "/datadrive/sid/text-segmentationl/data/choi",
    "wikidataset": "/datadrive/sid/wiki_727",
}

with open('config.json', 'w') as f:
    json.dump(jsondata, f)
```

Example 1:
```
root@f2f8e97440dc:/datadrive/sid/text-segmentation# python test_accuracy.py --model checkpoints/model_cpu.t7 --wiki --test
Running with threshold: 0.4
Loading word2vec ellapsed: 0.00523281097412 seconds
running on wikipedia
Traceback (most recent call last):
  File "test_accuracy.py", line 178, in <module>
    main(parser.parse_args())
  File "test_accuracy.py", line 79, in main
    model = torch.load(f)
  File "/usr/local/lib/python2.7/site-packages/torch/serialization.py", line 261, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python2.7/site-packages/torch/serialization.py", line 399, in _load
    magic_number = pickle_module.load(f)
cPickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```
Example 2:
```
root@f2f8e97440dc:/datadrive/sid/text-segmentation# python run_web_server.py --model checkpoints/model_cpu.t7 --test
Traceback (most recent call last):
  File "run_web_server.py", line 16, in <module>
    from webapp import app
  File "/datadrive/sid/text-segmentation/webapp/__init__.py", line 6, in <module>
    from webapp import views
  File "/datadrive/sid/text-segmentation/webapp/views.py", line 15, in <module>
    model = evaluate.load_model()
  File "/datadrive/sid/text-segmentation/evaluate.py", line 13, in load_model
    model = torch.load(f)
  File "/usr/local/lib/python2.7/site-packages/torch/serialization.py", line 261, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python2.7/site-packages/torch/serialization.py", line 399, in _load
    magic_number = pickle_module.load(f)
cPickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```

**Comment by erickrf** [comment]
I've seen the same error occurring when you open a pickle file and try to load the same data from it more than once.

**Comment by SamMohel** [comment]
i'm facing the same problem how can i fix it ? excuse me what do you mean by "open a pickle file and try to load the same data from it more than once" appreciating your help

**Comment by erickrf** [comment]
@SamMohel that happens if you open a file, call `pickle.load` (so the contents are loaded) and then call it again. Pickle has reached the end of the file and there's nothing left to read. If that is your case, you probably should close the file and open it again.

**Comment by SamMohel** [comment]
thanks for replying , excuse me you mean I should try like this
import pickle
 f = open('data.pkl', 'rb')
mydict = pickle.load(f)
f.close()
print (mydict)  as i got the same error
    mydict = pickle.load(f)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

**Comment by nutshell999** [comment]
The problem has been solved ?  I have the same.

**Comment by BitnaKeum** [comment]
In my case, it was not the problem of Pickle and was problem of the version of torch. 
I upgraded the version of torch then the problem has solved.
